- platform: generic
  name: Fabrizio
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.fabrizio_note4.attributes.latitude }},{{ states.device_tracker.fabrizio_note4.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.fabrizio_note4.attributes.latitude }},{{ states.device_tracker.fabrizio_note4.attributes.longitude }}
  limit_refetch_to_url_change: true