alias: giorno
initial_state: True
#  initial_state: True
hide_entity: False
trigger:
  - platform: time
    after: '{{ states.input_select.stop_mattina.state }}'
#    after: '07:30:00'
action:
  - service: climate.set_temperature
    data:
    entity_id: climate.termostato_caldaia
    temperature: '{{ states.input_slider.temp_giorno.state }}'
#        temperature: '16'
    operation_mode: Heat


