alias: mattina
#  initial_state: True
#hide_entity: False
trigger:
  platform: time
#  after: '{{ states.input_select.start_mattina.state }}'
  after: '05:30:00'
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: '{{ 6 <= now().hour < 8 }}'
action:
  service: climate.set_temperature
  data:
    entity_id: climate.termostato_caldaia
    temperature: '{{ states.input_slider.temp_mattina.state }}'
#    temperature: '22'
#    operation_mode: Heat
